services:
  norse-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAPBOX_API_KEY: ${NEXT_PUBLIC_MAPBOX_API_KEY}
        NEXT_PUBLIC_MAPBOX_STYLE_URL: ${NEXT_PUBLIC_MAPBOX_STYLE_URL}
        NEXT_PUBLIC_MAPLIBRE_STYLE_URL: ${NEXT_PUBLIC_MAPLIBRE_STYLE_URL}
        NEXT_PUBLIC_UMAMI_SCRIPT_URL: ${NEXT_PUBLIC_UMAMI_SCRIPT_URL}
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
    depends_on:
      norse-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DATABASE_URI: postgresql://norse-ng:norse-ng@norse-db:5432/norse-ng
      CACHE_REDIS_URI: redis://:norse-ng@redis:6379
      UMAMI_API_URL: http://umami:4444

  norse-db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: norse-ng
      POSTGRES_PASSWORD: norse-ng
      POSTGRES_DB: norse-ng
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U norse-ng -d norse-ng" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes --requirepass norse-ng

  prometheus:
    image: prom/prometheus:v3.9.1
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    depends_on:
      - norse-app
      - pushgateway

  pushgateway:
    image: prom/pushgateway:v1.10.0
    restart: always
    ports:
      - 9091:9091
    volumes:
      - pushgateway_data:/data
    command:
      - "--persistence.file=/data/pushgateway.data"

  grafana:
    image: grafana/grafana:12.3
    restart: always
    ports:
      - 3001:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  umami:
    image: ghcr.io/umami-software/umami:latest
    ports:
      - "4444:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      umami-db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:4444/api/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    ports:
      - "5431:5432"
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  pushgateway_data:
  grafana_data:
  umami-db-data:
