FROM node:24-bookworm-slim AS base

FROM base AS dependency-installer
WORKDIR /opt/norse/deps
COPY . .
RUN npm ci

FROM base AS runner
WORKDIR /opt/norse/app
RUN addgroup --system --gid 1001 payload \
  && adduser --system --uid 1001 payload \
  && chown payload:payload /opt/norse/app
COPY --from=dependency-installer --chown=payload:payload /opt/norse/deps/src ./src
COPY --from=dependency-installer --chown=payload:payload /opt/norse/deps/package.json ./package.json
COPY --from=dependency-installer --chown=payload:payload /opt/norse/deps/node_modules ./node_modules
COPY --from=dependency-installer --chown=payload:payload /opt/norse/deps/tsconfig.json ./tsconfig.json
USER payload
ENV PAYLOAD_CONFIG_PATH=src/payload/payload-config.ts
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
CMD ["npm", "run", "payload", "migrate"]