export const ELASTIC_RESULT_INDEX =
  process.env.NEXT_PUBLIC_ELASTIC_RESULT_INDEX;
export const ELASTIC_TAXONOMY_INDEX =
  process.env.NEXT_PUBLIC_ELASTIC_TAXONOMY_INDEX;
export const MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY;
export const GTM_CONTAINER_ID = process.env.NEXT_PUBLIC_GTM_CONTAINER_ID;
