/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    'tenant-media': TenantMedia;
    'resource-directories': ResourceDirectory;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-media': TenantMediaSelect<false> | TenantMediaSelect<true>;
    'resource-directories': ResourceDirectoriesSelect<false> | ResourceDirectoriesSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale:
    | 'am'
    | 'ar'
    | 'de'
    | 'en'
    | 'es'
    | 'fi'
    | 'fil'
    | 'ff'
    | 'fr'
    | 'hi'
    | 'hr'
    | 'ht'
    | 'ko'
    | 'km'
    | 'ne'
    | 'om'
    | 'pl'
    | 'pt'
    | 'ru'
    | 'so'
    | 'sw'
    | 'uk'
    | 'vi'
    | 'yue'
    | 'zh-Hans'
    | 'zh-Hant';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      translateTopics: TaskTranslateTopics;
      warmCache: TaskWarmCache;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'support' | 'tenant')[];
  tenants?:
    | {
        tenant: string | Tenant;
        roles: ('tenant-admin' | 'tenant-editor')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  trustedDomains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  enabledLocales: (
    | 'am'
    | 'ar'
    | 'de'
    | 'en'
    | 'es'
    | 'fi'
    | 'fil'
    | 'ff'
    | 'fr'
    | 'hi'
    | 'hr'
    | 'ht'
    | 'ko'
    | 'km'
    | 'ne'
    | 'om'
    | 'pl'
    | 'pt'
    | 'ru'
    | 'so'
    | 'sw'
    | 'uk'
    | 'vi'
    | 'yue'
    | 'zh-Hans'
    | 'zh-Hant'
  )[];
  defaultLocale:
    | 'am'
    | 'ar'
    | 'de'
    | 'en'
    | 'es'
    | 'fi'
    | 'fil'
    | 'ff'
    | 'fr'
    | 'hi'
    | 'hr'
    | 'ht'
    | 'ko'
    | 'km'
    | 'ne'
    | 'om'
    | 'pl'
    | 'pt'
    | 'ru'
    | 'so'
    | 'sw'
    | 'uk'
    | 'vi'
    | 'yue'
    | 'zh-Hans'
    | 'zh-Hant';
  services: {
    resourceDirectory?: boolean | null;
  };
  auth: {
    realmId: string;
    keycloakSecret?: string | null;
    keycloakIssuer?: string | null;
    nextAuthSecret?: string | null;
  };
  common?: {
    gtmContainerId?: string | null;
    matomoContainerUrl?: string | null;
  };
  twilio?: {
    phoneNumber?: string | null;
    apiKey?: string | null;
    apiKeySid?: string | null;
    accountSid?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-media".
 */
export interface TenantMedia {
  id: number;
  tenant?: (string | null) | Tenant;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-directories".
 */
export interface ResourceDirectory {
  tenant?: (string | null) | Tenant;
  id: string;
  name: string;
  _translationMeta?: {
    lastTranslatedAt?: string | null;
    translatedBy?: ('auto' | 'manual') | null;
    engine?: ('azure' | 'google') | null;
  };
  accessibility?: {
    fontSizeAdjustment?: ('150%' | '175%' | '200%') | null;
  };
  common?: {
    alert?:
      | {
          text: string;
          buttonText?: string | null;
          url?: string | null;
          openInNewTab?: boolean | null;
          variant?: ('destructive' | 'default') | null;
          id?: string | null;
        }[]
      | null;
    smsProvider?: 'Twilio' | null;
    customDataProvidersHeading?: string | null;
    dataProviders?:
      | {
          name?: string | null;
          url?: string | null;
          openInNewTab?: boolean | null;
          logo?: (number | null) | TenantMedia;
          id?: string | null;
        }[]
      | null;
  };
  brand: {
    logo: number | TenantMedia;
    favicon: number | TenantMedia;
    hero?: (number | null) | TenantMedia;
    openGraph?: (number | null) | TenantMedia;
    copyright?: string | null;
    feedbackUrl?: string | null;
    phoneNumber?: string | null;
    theme: {
      primaryColor: string;
      secondaryColor: string;
      borderRadius: string;
    };
    meta?: {
      title?: string | null;
      description?: string | null;
    };
  };
  header?: {
    customMenu?:
      | {
          name: string;
          href?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    customHomeUrl?: string | null;
    searchUrl?: string | null;
    safeExit?: {
      enabled?: boolean | null;
      url?: string | null;
      openInNewTab?: boolean | null;
      text?: string | null;
    };
  };
  footer?: {
    disclaimer?: string | null;
    customMenu?:
      | {
          name: string;
          href?: string | null;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  suggestions: {
    value: string;
    taxonomies: string;
    id?: string | null;
  }[];
  topics?: {
    backText?: string | null;
    customHeading?: string | null;
    iconSize?: ('small' | 'medium') | null;
    imageBorderRadius?: number | null;
    list?:
      | {
          name: string;
          image?: (number | null) | TenantMedia;
          href?: string | null;
          openInNewTab?: boolean | null;
          subtopics?:
            | {
                name: string;
                queryType?: ('taxonomy' | 'text' | 'link') | null;
                query?: string | null;
                href?: string | null;
                openInNewTab?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  resource?: {
    lastAssuredText?: string | null;
  };
  search: {
    texts?: {
      title?: string | null;
      queryInputPlaceholder?: string | null;
      locationInputPlaceholder?: string | null;
      noResultsFallbackText?: string | null;
    };
    searchSettings: {
      resultsLimit: number;
      radiusSelectValues?:
        | {
            value: number;
            id?: string | null;
          }[]
        | null;
      /**
       * Must match one of the radius values above
       */
      defaultRadius?: number | null;
    };
    facets?:
      | {
          name?: string | null;
          facet: string;
          id?: string | null;
        }[]
      | null;
    map: {
      center: string;
      zoom: number;
    };
  };
  newLayout?: {
    enabled?: boolean | null;
    headerStart?: string | null;
    headerEnd?: string | null;
    hero?: (number | null) | TenantMedia;
    logo?: (number | null) | TenantMedia;
    callouts?: {
      options?:
        | {
            type: 'Call' | 'SMS' | 'Chat' | 'Email';
            customImg?: (number | null) | TenantMedia;
            description?: string | null;
            title?: string | null;
            url?: string | null;
            openInNewTab?: boolean | null;
            id?: string | null;
          }[]
        | null;
      title?: string | null;
    };
  };
  privacyPolicyPage?: {
    enabled?: boolean | null;
    title?: string | null;
    content?: string | null;
  };
  termsOfUsePage?: {
    enabled?: boolean | null;
    title?: string | null;
    content?: string | null;
  };
  featureFlags?: {
    hideCategoriesHeading?: boolean | null;
    hideDataProvidersHeading?: boolean | null;
    showResourceAttribution?: boolean | null;
    showResourceCategories?: boolean | null;
    showResourceLastAssuredDate?: boolean | null;
    showHomePageTour?: boolean | null;
    requireUserLocation?: boolean | null;
    showSearchAndResourceServiceName?: boolean | null;
    showSuggestionListTaxonomyBadge?: boolean | null;
    showUseMyLocationButtonOnDesktop?: boolean | null;
    showPrintButton?: boolean | null;
    turnResourceCardTaxonomiesIntoLinks?: boolean | null;
    useHybridSemanticSearch?: boolean | null;
    showFeedbackButtonGlobal?: boolean | null;
    showFeedbackButtonOnResourcePages?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'translateTopics' | 'warmCache';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'translateTopics' | 'warmCache') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-media';
        value: number | TenantMedia;
      } | null)
    | ({
        relationTo: 'resource-directories';
        value: string | ResourceDirectory;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  trustedDomains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  enabledLocales?: T;
  defaultLocale?: T;
  services?:
    | T
    | {
        resourceDirectory?: T;
      };
  auth?:
    | T
    | {
        realmId?: T;
        keycloakSecret?: T;
        keycloakIssuer?: T;
        nextAuthSecret?: T;
      };
  common?:
    | T
    | {
        gtmContainerId?: T;
        matomoContainerUrl?: T;
      };
  twilio?:
    | T
    | {
        phoneNumber?: T;
        apiKey?: T;
        apiKeySid?: T;
        accountSid?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-media_select".
 */
export interface TenantMediaSelect<T extends boolean = true> {
  tenant?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-directories_select".
 */
export interface ResourceDirectoriesSelect<T extends boolean = true> {
  tenant?: T;
  id?: T;
  name?: T;
  _translationMeta?:
    | T
    | {
        lastTranslatedAt?: T;
        translatedBy?: T;
        engine?: T;
      };
  accessibility?:
    | T
    | {
        fontSizeAdjustment?: T;
      };
  common?:
    | T
    | {
        alert?:
          | T
          | {
              text?: T;
              buttonText?: T;
              url?: T;
              openInNewTab?: T;
              variant?: T;
              id?: T;
            };
        smsProvider?: T;
        customDataProvidersHeading?: T;
        dataProviders?:
          | T
          | {
              name?: T;
              url?: T;
              openInNewTab?: T;
              logo?: T;
              id?: T;
            };
      };
  brand?:
    | T
    | {
        logo?: T;
        favicon?: T;
        hero?: T;
        openGraph?: T;
        copyright?: T;
        feedbackUrl?: T;
        phoneNumber?: T;
        theme?:
          | T
          | {
              primaryColor?: T;
              secondaryColor?: T;
              borderRadius?: T;
            };
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  header?:
    | T
    | {
        customMenu?:
          | T
          | {
              name?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
        customHomeUrl?: T;
        searchUrl?: T;
        safeExit?:
          | T
          | {
              enabled?: T;
              url?: T;
              openInNewTab?: T;
              text?: T;
            };
      };
  footer?:
    | T
    | {
        disclaimer?: T;
        customMenu?:
          | T
          | {
              name?: T;
              href?: T;
              openInNewTab?: T;
              id?: T;
            };
      };
  suggestions?:
    | T
    | {
        value?: T;
        taxonomies?: T;
        id?: T;
      };
  topics?:
    | T
    | {
        backText?: T;
        customHeading?: T;
        iconSize?: T;
        imageBorderRadius?: T;
        list?:
          | T
          | {
              name?: T;
              image?: T;
              href?: T;
              openInNewTab?: T;
              subtopics?:
                | T
                | {
                    name?: T;
                    queryType?: T;
                    query?: T;
                    href?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  resource?:
    | T
    | {
        lastAssuredText?: T;
      };
  search?:
    | T
    | {
        texts?:
          | T
          | {
              title?: T;
              queryInputPlaceholder?: T;
              locationInputPlaceholder?: T;
              noResultsFallbackText?: T;
            };
        searchSettings?:
          | T
          | {
              resultsLimit?: T;
              radiusSelectValues?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              defaultRadius?: T;
            };
        facets?:
          | T
          | {
              name?: T;
              facet?: T;
              id?: T;
            };
        map?:
          | T
          | {
              center?: T;
              zoom?: T;
            };
      };
  newLayout?:
    | T
    | {
        enabled?: T;
        headerStart?: T;
        headerEnd?: T;
        hero?: T;
        logo?: T;
        callouts?:
          | T
          | {
              options?:
                | T
                | {
                    type?: T;
                    customImg?: T;
                    description?: T;
                    title?: T;
                    url?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              title?: T;
            };
      };
  privacyPolicyPage?:
    | T
    | {
        enabled?: T;
        title?: T;
        content?: T;
      };
  termsOfUsePage?:
    | T
    | {
        enabled?: T;
        title?: T;
        content?: T;
      };
  featureFlags?:
    | T
    | {
        hideCategoriesHeading?: T;
        hideDataProvidersHeading?: T;
        showResourceAttribution?: T;
        showResourceCategories?: T;
        showResourceLastAssuredDate?: T;
        showHomePageTour?: T;
        requireUserLocation?: T;
        showSearchAndResourceServiceName?: T;
        showSuggestionListTaxonomyBadge?: T;
        showUseMyLocationButtonOnDesktop?: T;
        showPrintButton?: T;
        turnResourceCardTaxonomiesIntoLinks?: T;
        useHybridSemanticSearch?: T;
        showFeedbackButtonGlobal?: T;
        showFeedbackButtonOnResourcePages?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTranslateTopics".
 */
export interface TaskTranslateTopics {
  input: {
    tenantId: string;
    locales: {
      locale?: string | null;
    }[];
    engine: 'azure' | 'google';
    force?: boolean | null;
  };
  output: {
    success: boolean;
    translated: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskWarmCache".
 */
export interface TaskWarmCache {
  input: {
    domains?:
      | {
          domain?: string | null;
        }[]
      | null;
  };
  output: {
    success: boolean;
    warmedTenants: number;
    warmedResourceDirectories: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}