export enum SearchCardComponentId {
  ATTRIBUTION = 'attribution',
  BADGES = 'badges',
  RESOURCE_NAME = 'resourceName',
  SERVICE_NAME = 'serviceName',
  ELIGIBILITY = 'eligibility',
  APPLICATION_PROCESS = 'applicationProcess',
  LOCATION_NAME = 'locationName',
  LOCATION_NAME_SUBTITLE = 'locationNameSubtitle',
  ADDRESS = 'address',
  PHONE = 'phone',
  WEBSITE = 'website',
  DESCRIPTION = 'description',
  CATEGORIES = 'categories',
  ACTION_BUTTONS = 'actionButtons',
  SEPARATOR = 'separator',
  CUSTOM_ATTRIBUTE = 'customAttribute',
}
